export const oneUI85Data = {
    // أيقونات التطبيقات الأساسية
    apps: [
        { id: "apps", name: "Apps", file: "apps.png" },
        { id: "browser", name: "Samsung Internet", file: "browser.png" },
        { id: "calculator", name: "Calculator", file: "calculator.png" },
        { id: "calendar", name: "Calendar", file: "calendar.png" },
        { id: "calendar_google", name: "Google Calendar", file: "calendar_google.png" },
        { id: "camera", name: "Camera", file: "camera.png" },
        { id: "chat", name: "Chat", file: "chat.png" },
        { id: "chrome", name: "Google Chrome", file: "chrome.png" },
        { id: "clock", name: "Clock", file: "clock.png" },
        { id: "contacts", name: "Contacts", file: "contacts.png" },
        { id: "drive", name: "Google Drive", file: "drive.png" },
        { id: "edge", name: "Microsoft Edge", file: "edge.png" },
        { id: "find_my_mobile", name: "Find My Mobile", file: "find_my_mobile.png" },
        { id: "gallery", name: "Gallery", file: "gallery.png" },
        { id: "gallery_google", name: "Google Gallery", file: "gallery_google.png" },
        { id: "game_launcher", name: "Game Launcher", file: "game_launcher.png" },
        { id: "gemini", name: "Gemini AI", file: "gemini.png" },
        { id: "good_lock", name: "Good Lock", file: "good_lock.png" },
        { id: "google", name: "Google", file: "google.png" },
        { id: "meet", name: "Google Meet", file: "meet.png" },
        { id: "members", name: "Samsung Members", file: "members.png" },
        { id: "messages", name: "Messages", file: "messages.png" },
        { id: "messages_google", name: "Google Messages", file: "messages_google.png" },
        { id: "music", name: "Samsung Music", file: "music.png" },
        { id: "my_files", name: "My Files", file: "my_files.png" },
        { id: "netflix", name: "Netflix", file: "netflix.png" },
        { id: "news", name: "Samsung News", file: "news.png" },
        { id: "notes", name: "Samsung Notes", file: "notes.png" },
        { id: "onedrive", name: "OneDrive", file: "onedrive.png" },
        { id: "outlook", name: "Outlook", file: "outlook.png" },
        { id: "pay", name: "Samsung Pay", file: "pay.png" },
        { id: "pen_up", name: "PENUP", file: "pen_up.png" },
        { id: "phone", name: "Phone", file: "phone.png" },
        { id: "photos", name: "Google Photos", file: "photos.png" },
        { id: "play_store", name: "Play Store", file: "play_store.png" },
        { id: "radio", name: "Radio", file: "radio.png" },
        { id: "settings", name: "Settings", file: "settings.png" },
        { id: "smart_switch", name: "Smart Switch", file: "smart_switch.png" },
        { id: "smartthings", name: "SmartThings", file: "smartthings.png" },
        { id: "spotify_lite", name: "Spotify Lite", file: "spotify_lite.png" },
        { id: "themes", name: "Galaxy Themes", file: "themes.png" },
        { id: "voice_recorder", name: "Voice Recorder", file: "Voice_Recoder.png" },
        { id: "weather", name: "Weather", file: "weather.png" },
        { id: "youtube", name: "YouTube", file: "YouTube.png" }
    ],
    // عناصر الواجهة والرسوميات (Sprites) لمحرك Construct 2/3
    interface: [
        { name: "Background", file: "batterybackground-sheet0.png" },
        { name: "Live Clock", file: "liveclock-sheet0.png" },
        { name: "Live Music", file: "livemusic-sheet0.png" },
        { name: "App Start Anim", file: "appstart-sheet0.png" },
        { name: "Navigation Bar", file: "livebar-sheet0.png" },
        { name: "Status Bar Icons", file: "sprite16-sheet0.png" },
        { name: "Keyboard View", file: "sprite42-sheet0.png" },
        { name: "Folder View", file: "sprite21-sheet0.png" },
        { name: "Search Icon", file: "sprite29-sheet0.png" }
    ],
    // الخطوط المستخدمة
    fonts: ["spritefont.png", "spritefont2.png", "spritefont3.png"]
};